//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Tab
    {
        public int Admin_Id { get; set; }
        public string Admin_Name { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
    }
}
