//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Tab
    {
        public int Appl_Id { get; set; }
        public int User_Id { get; set; }
        public int Job_Id { get; set; }
        public string Appl_Date { get; set; }
        public string Resume_Url { get; set; }
        public string Status { get; set; }
    }
}
