//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Tab
    {
        public int Job_Id { get; set; }
        public int Admin_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Experiance { get; set; }
        public string Skills { get; set; }
        public string Location { get; set; }
        public string Job_Status { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
    }
}
