//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Job_Portal_WebsiteEntities : DbContext
    {
        public Job_Portal_WebsiteEntities()
            : base("name=Job_Portal_WebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Tab> Admin_Tab { get; set; }
        public virtual DbSet<Application_Tab> Application_Tab { get; set; }
        public virtual DbSet<Job_Tab> Job_Tab { get; set; }
        public virtual DbSet<Login_Tab> Login_Tab { get; set; }
        public virtual DbSet<User_Tab> User_Tab { get; set; }
    
        public virtual int sp_AdminReg(Nullable<int> aid, string ana, string cna, string cdes)
        {
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var anaParameter = ana != null ?
                new ObjectParameter("ana", ana) :
                new ObjectParameter("ana", typeof(string));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var cdesParameter = cdes != null ?
                new ObjectParameter("cdes", cdes) :
                new ObjectParameter("cdes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AdminReg", aidParameter, anaParameter, cnaParameter, cdesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginCount(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginCount", unaParameter, pwdParameter);
        }
    
        public virtual int sp_LoginInsert(Nullable<int> rid, string una, string pwd, string typ)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var typParameter = typ != null ?
                new ObjectParameter("typ", typ) :
                new ObjectParameter("typ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LoginInsert", ridParameter, unaParameter, pwdParameter, typParameter);
        }
    
        public virtual ObjectResult<string> sp_LoginType(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_LoginType", unaParameter, pwdParameter);
        }
    
        public virtual int sp_UserReg(Nullable<int> uid, string una, string umil, Nullable<System.DateTime> dob, Nullable<int> ph, Nullable<int> exp, string skl, string qul, string sts)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var umilParameter = umil != null ?
                new ObjectParameter("umil", umil) :
                new ObjectParameter("umil", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phParameter = ph.HasValue ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(int));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            var qulParameter = qul != null ?
                new ObjectParameter("qul", qul) :
                new ObjectParameter("qul", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UserReg", uidParameter, unaParameter, umilParameter, dobParameter, phParameter, expParameter, sklParameter, qulParameter, stsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_regCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_regCount");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginIdCount(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginIdCount", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AdminId(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AdminId", unaParameter, pwdParameter);
        }
    
        public virtual int sp_JobInsert(Nullable<int> aid, string tle, string des, string exp, string skl, string loc, string stas, string start, string end)
        {
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var tleParameter = tle != null ?
                new ObjectParameter("tle", tle) :
                new ObjectParameter("tle", typeof(string));
    
            var desParameter = des != null ?
                new ObjectParameter("des", des) :
                new ObjectParameter("des", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var stasParameter = stas != null ?
                new ObjectParameter("stas", stas) :
                new ObjectParameter("stas", typeof(string));
    
            var startParameter = start != null ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(string));
    
            var endParameter = end != null ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_JobInsert", aidParameter, tleParameter, desParameter, expParameter, sklParameter, locParameter, stasParameter, startParameter, endParameter);
        }
    }
}
