//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tab
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Email { get; set; }
        public System.DateTime User_Dob { get; set; }
        public int Phone { get; set; }
        public int Experiance_In_year { get; set; }
        public string Skills { get; set; }
        public string Qualification { get; set; }
        public string Status { get; set; }
    }
}
